version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '6500:5432'
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker123
      POSTGRESQL_DATABASE: nestjs_auth
    volumes:
      - nestjs_auth_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - nestjs_auth_redis_data:/bitnami/redis/data
    
volumes:
  nestjs_auth_pg_data:
  nestjs_auth_redis_data: